EXEC dbo.addLanuageLabel 'English',  'A connection to the database could not be established, please contact your system administrator.', 'French', 'Une connexion à la base de données n''a pas pu être établie, veuillez contacter votre administrateur système.';
EXEC dbo.addLanuageLabel 'English',  'A database error has occurred!', 'French', 'Une erreur de base de données s''est produite!';
EXEC dbo.addLanuageLabel 'English',  'A password must be provided!', 'French', 'Un mot de passe doit être fourni!';
EXEC dbo.addLanuageLabel 'English',  'A username must be provided!', 'French', 'Un nom d''utilisateur doit être fourni!';
EXEC dbo.addLanuageLabel 'English',  'Access Denied', 'French', 'Accès Refusé';
EXEC dbo.addLanuageLabel 'English',  'Account - Contact', 'French', 'Compte - Contact';
EXEC dbo.addLanuageLabel 'English',  'Account Contacts', 'French', 'Contacts du Compte';
EXEC dbo.addLanuageLabel 'English',  'Account Historic Event Count', 'French', 'Compte d''Événements Historiques du Compte';
EXEC dbo.addLanuageLabel 'English',  'Account by Contacts', 'French', 'Compte par Contacts';
EXEC dbo.addLanuageLabel 'English',  'Account by Locality', 'French', 'Compte par Localité';
EXEC dbo.addLanuageLabel 'English',  'ActiveRecord', 'French', 'Enregistrement Actif';
EXEC dbo.addLanuageLabel 'English',  'Add attachments', 'French', 'Ajouter des Pièces Jointes';
EXEC dbo.addLanuageLabel 'English',  'Administration', 'French', 'Administration';
EXEC dbo.addLanuageLabel 'English',  'Advanced After', 'French', 'Avancé Après';
EXEC dbo.addLanuageLabel 'English',  'Advanced Before', 'French', 'Avancé Avant';
EXEC dbo.addLanuageLabel 'English',  'Advanced Between', 'French', 'Avancé Entre';
EXEC dbo.addLanuageLabel 'English',  'Advanced On', 'French', 'Avancé à';
EXEC dbo.addLanuageLabel 'English',  'Alternative Contacts', 'French', 'Contacts Alternatifs';
EXEC dbo.addLanuageLabel 'English',  'Amount of Event Reoccurences', 'French', 'Nombre de Réapparitions d''Occurrences';
EXEC dbo.addLanuageLabel 'English',  'An email containing the link to reset your password has been sent to you.', 'French', 'Une courriel contenant le lien pour réinitialiser votre mot de passe vous a été envoyé.';
EXEC dbo.addLanuageLabel 'English',  'An error has occurred while executing the request.', 'French', 'Une erreur s''est produite lors de l''exécution de la demande.';
EXEC dbo.addLanuageLabel 'English',  'An issue has occurred, Please contact your Administator.', 'French', 'Un problème est survenu. Veuillez contacter votre administrateur.';
EXEC dbo.addLanuageLabel 'English',  'Appearance Location', 'French', 'Emplacement d''Apparence';
EXEC dbo.addLanuageLabel 'English',  'Application URL', 'French', 'URL de l''Application';
EXEC dbo.addLanuageLabel 'English',  'Are there any witnesses ?', 'French', 'Y-a-t-il des témoins?';
EXEC dbo.addLanuageLabel 'English',  'Are you sure you want to remove this attachment?', 'French', 'Voulez-vous vraiment supprimer cette pièce jointe?';
EXEC dbo.addLanuageLabel 'English',  'Are you sure you want to save this Incident?', 'French', 'Êtes-vous sûr de vouloir enregistrer cet Incident?';
EXEC dbo.addLanuageLabel 'English',  'Are you sure you wish to Complete the Escalation Procedure(s)?', 'French', 'Êtes-vous sûr de vouloir terminer la (les) Procédure (s) d''Escalade?';
EXEC dbo.addLanuageLabel 'English',  'Asset cannot be deleted as it is linked to :', 'French', 'L''élément ne peut pas être supprimé car il est lié à:';
EXEC dbo.addLanuageLabel 'English',  'Assets', 'French', 'Actifs';
EXEC dbo.addLanuageLabel 'English',  'Attachment is linked to an Escalation Procedure and cannot be deleted.', 'French', 'La Pièce Jointe est liée à une Procédure d''Escalade et ne peut pas être supprimée.';
EXEC dbo.addLanuageLabel 'English',  'Authorized Individual', 'French', 'Personne Autorisée';
EXEC dbo.addLanuageLabel 'English',  'Back', 'French', 'Retour';
EXEC dbo.addLanuageLabel 'English',  'Bulk Notification Localities', 'French', 'Localités de Notification en Masse';
EXEC dbo.addLanuageLabel 'English',  'Business Hours', 'French', 'Heures de Travail';
EXEC dbo.addLanuageLabel 'English',  'Cancel', 'French', 'Annuler';
EXEC dbo.addLanuageLabel 'English',  'Cannot continue with action, check Financial Impact Validation Rule(s) below', 'French', 'Impossible de poursuivre l''action, vérifiez les règles de validation de l''impact financier ci-dessous';
EXEC dbo.addLanuageLabel 'English',  'Car Model', 'French', 'Modèle de Voiture';
EXEC dbo.addLanuageLabel 'English',  'Categories', 'French', 'Catégories';
EXEC dbo.addLanuageLabel 'English',  'Category per Locality Scoping Rules are already calculating!', 'French', 'Les règles de cadrage des catégories par localité sont déjà en cours de calcul!';
EXEC dbo.addLanuageLabel 'English',  'Category', 'French', 'Catégorie';
EXEC dbo.addLanuageLabel 'English',  'Change Motivation required.', 'French', 'Changement de motivation requis.';
EXEC dbo.addLanuageLabel 'English',  'Change Password', 'French', 'Changer le Mot de Passe';
EXEC dbo.addLanuageLabel 'English',  'Change to Translate', 'French', 'Changer pour Traduire';
EXEC dbo.addLanuageLabel 'English',  'Check Duplicate Settings', 'French', 'Vérifier les Paramètres en Double';
EXEC dbo.addLanuageLabel 'English',  'Checking Super Search Status...', 'French', 'Vérification de l''État de la Super Recherche ...';
EXEC dbo.addLanuageLabel 'English',  'Checklist Category Subcategory Intersection', 'French', 'Liste de Contrôle Intersection de Sous-catégories de Catégories';
EXEC dbo.addLanuageLabel 'English',  'Checklist Response Rules', 'French', 'Règles de Réponse de la Liste de Contrôle';
EXEC dbo.addLanuageLabel 'English',  'Checklist Responsible Individual Category Scope Index Table', 'French', 'Tableau d''Index de la Portée des Catégories de Individus Responsables de la Liste de Contrôle';
EXEC dbo.addLanuageLabel 'English',  'Checklist Schedules', 'French', 'Programmes de la Liste de Contrôle';
EXEC dbo.addLanuageLabel 'English',  'Checklist Subcategory Score', 'French', 'Score de la Sous-Catégorie de la Liste de Contrôle';
EXEC dbo.addLanuageLabel 'English',  'Checklists', 'French', 'Listes de Contrôle';
EXEC dbo.addLanuageLabel 'English',  'Click an item to select it.', 'French', 'Cliquez sur un élément pour le sélectionner.';
EXEC dbo.addLanuageLabel 'English',  'Close', 'French', 'Fermer';
EXEC dbo.addLanuageLabel 'English',  'Collab Share Scoping', 'French', 'Portée du Partage de Collaboration';
EXEC dbo.addLanuageLabel 'English',  'Commands', 'French', 'Commandes';
EXEC dbo.addLanuageLabel 'English',  'Components', 'French', 'Composants';
EXEC dbo.addLanuageLabel 'English',  'Confirm Password', 'French', 'Confirmez le Mot de Passe';
EXEC dbo.addLanuageLabel 'English',  'Could not retrieve token, please resend!', 'French', 'Impossible de récupérer le jeton, veuillez renvoyer!';
EXEC dbo.addLanuageLabel 'English',  'Could not validate current system user', 'French', 'Impossible de valider l''utilisateur système actuel';
EXEC dbo.addLanuageLabel 'English',  'Criminal Records', 'French', 'Casiers Judiciaires';
EXEC dbo.addLanuageLabel 'English',  'Custom Values', 'French', 'Valeurs Personnalisées';
EXEC dbo.addLanuageLabel 'English',  'Database Error', 'French', 'Erreur de la Base de Données';
EXEC dbo.addLanuageLabel 'English',  'Delete', 'French', 'Supprimer';
EXEC dbo.addLanuageLabel 'English',  'Directions', 'French', 'Instructions';
EXEC dbo.addLanuageLabel 'English',  'Disaster Mode locality Rules', 'French', 'Règles de Localité en Mode Catastrophe';
EXEC dbo.addLanuageLabel 'English',  'Do you want to use the complainant details?', 'French', 'Voulez-vous utiliser les détails du plaignant?';
EXEC dbo.addLanuageLabel 'English',  'Edit Access', 'French', 'Accès Modifier';
EXEC dbo.addLanuageLabel 'English',  'Edit', 'French', 'Éditer';
EXEC dbo.addLanuageLabel 'English',  'Email Reference Number Option', 'French', 'Option Numéro de Référence Courriel';
EXEC dbo.addLanuageLabel 'English',  'Employee Locality Groups', 'French', 'Groupes de Localités d''Employés';
EXEC dbo.addLanuageLabel 'English',  'Employee Security Clearances', 'French', 'Autorisations de Sécurité des Employés';
EXEC dbo.addLanuageLabel 'English',  'End Translation', 'French', 'Terminer la Traduction';
EXEC dbo.addLanuageLabel 'English',  'Entries', 'French', 'Entrées';
EXEC dbo.addLanuageLabel 'English',  'Error while updating license!', 'French', 'Erreur lors de la mise à jour de la licence!';
EXEC dbo.addLanuageLabel 'English',  'Escalation Individual Type Scoping', 'French', 'Portée du Type Individuel d''Escalade';
EXEC dbo.addLanuageLabel 'English',  'Escalation Occurrence Category Scope', 'French', 'Portée de la Catégorie d''Occurrence d''Escalade';
EXEC dbo.addLanuageLabel 'English',  'Escalation Step Rule Occurrence', 'French', 'Règle Occurrence d''Étape d''Escalade';
EXEC dbo.addLanuageLabel 'English',  'Escalation Steps', 'French', 'Étapes d''Escalade';
EXEC dbo.addLanuageLabel 'English',  'Escalation Vehicle Category Scope', 'French', 'Portée de la Catégorie de Véhicule d''Escalade';
EXEC dbo.addLanuageLabel 'English',  'Event Created Date', 'French', 'Date de Création de l''Événement';
EXEC dbo.addLanuageLabel 'English',  'External Job Card', 'French', 'Carte de Travail Externe';
EXEC dbo.addLanuageLabel 'English',  'External Reference Numbers', 'French', 'Numéros de Référence Externes';
EXEC dbo.addLanuageLabel 'English',  'External Reference Type is required, please ensure all required references are present', 'French', 'Le Type de Référence Externe est requis, veuillez vous assurer que toutes les références requises sont présentes';
EXEC dbo.addLanuageLabel 'English',  'External Reference', 'French', 'Référence Externe';
EXEC dbo.addLanuageLabel 'English',  'External reference number that was specified, already exists.', 'French', 'Numéro de référence externe spécifié, existe déjà.';
EXEC dbo.addLanuageLabel 'English',  'Feedback', 'French', 'Rétroaction';
EXEC dbo.addLanuageLabel 'English',  'Finalise Event', 'French', 'Finaliser l''Événement';
EXEC dbo.addLanuageLabel 'English',  'Financial Impact cannot be deleted as its linked to :', 'French', 'L''Impact Financier ne peut pas être supprimé car il est lié à:';
EXEC dbo.addLanuageLabel 'English',  'First Name', 'French', 'Prenom';
EXEC dbo.addLanuageLabel 'English',  'Flag as Dispatch', 'French', 'Marquer comme Envoi';
EXEC dbo.addLanuageLabel 'English',  'Full Step', 'French', 'Étape Complète';
EXEC dbo.addLanuageLabel 'English',  'General Error', 'French', 'Erreur Générale';
EXEC dbo.addLanuageLabel 'English',  'Global Turnaround Time', 'French', 'Délai d''Exécution Global';
EXEC dbo.addLanuageLabel 'English',  'Has a Suspension linked to an Incident.', 'French', 'A une Suspension liée à un Incident.';
EXEC dbo.addLanuageLabel 'English',  'Has an Arrest Record.', 'French', 'A un Dossier d''Arrestation.';
EXEC dbo.addLanuageLabel 'English',  'Has been selected as a "Guard" for an  Incident/Occurrence.', 'French', 'A été sélectionné comme «Gardien» pour un Incident / Occurrence.';
EXEC dbo.addLanuageLabel 'English',  'Has been selected as a "ReportedBy" for an Incident/Occurrence.', 'French', 'A été sélectionné comme «Rapporté Par» pour un Incident / Occurrence.';
EXEC dbo.addLanuageLabel 'English',  'Has been selected as a "Stakeholder" for an  Incident/Occurrence.', 'French', 'A été sélectionné comme «Partie Prenante» pour un Incident / Occurrence.';
EXEC dbo.addLanuageLabel 'English',  'Has been selected as a "Supervisor" for an  Incident/Occurrence.', 'French', 'A été sélectionné comme «Superviseur» pour un Incident / Occurrence.';
EXEC dbo.addLanuageLabel 'English',  'Has been selected as a recipient for an Escalation Step Notification.', 'French', 'A été sélectionné comme destinataire pour une Notification d''Étape d''Escalade.';
EXEC dbo.addLanuageLabel 'English',  'Has been selected as an Escalation Procedure feedback.', 'French', 'A été sélectionné comme commentaire de Procédure d''Escalade.';
EXEC dbo.addLanuageLabel 'English',  'Help', 'French', 'Aidez-moi';
EXEC dbo.addLanuageLabel 'English',  'Hide App URL', 'French', 'Cacher l''URL de l''application';
EXEC dbo.addLanuageLabel 'English',  'Hide Licenses', 'French', 'Cahcer les Licences';
EXEC dbo.addLanuageLabel 'English',  'Hide', 'French', 'Cacher';
EXEC dbo.addLanuageLabel 'English',  'Historc Alarm Events', 'French', 'Événements d''Alarme d''Historique';
EXEC dbo.addLanuageLabel 'English',  'Historic Alarm Event', 'French', 'Événement d''Alarme Historique';
EXEC dbo.addLanuageLabel 'English',  'Historic Event Category', 'French', 'Catégorie d''Événement Historique';
EXEC dbo.addLanuageLabel 'English',  'Historic Events Hidden Menu', 'French', 'Menu caché des événements historiques';
EXEC dbo.addLanuageLabel 'English',  'Historic Events', 'French', 'Événements Historiques';
EXEC dbo.addLanuageLabel 'English',  'Home', 'French', 'Accueil';
EXEC dbo.addLanuageLabel 'English',  'ID Number', 'French', 'Numéro d''Identification';
EXEC dbo.addLanuageLabel 'English',  'ID number that was specified, already exists.', 'French', 'Le numéro d''identification spécifié existe déjà.';
EXEC dbo.addLanuageLabel 'English',  'IMPI Message Localities', 'French', 'Localités de Messages IMPI';
EXEC dbo.addLanuageLabel 'English',  'IMPI Message Locality Groups', 'French', 'Groupes de Localités de Message IMPI';
EXEC dbo.addLanuageLabel 'English',  'In Translation Mode', 'French', 'En mode traduction';
EXEC dbo.addLanuageLabel 'English',  'Incompatible Browser !', 'French', 'Navigateur Incompatible';
EXEC dbo.addLanuageLabel 'English',  'Incorrect Pin!', 'French', 'Pin incorrect!';
EXEC dbo.addLanuageLabel 'English',  'Individual Profilies', 'French', 'Profils d''Individus';
EXEC dbo.addLanuageLabel 'English',  'Individual Type Scope', 'French', 'Portée de Type Individuel';
EXEC dbo.addLanuageLabel 'English',  'Instacom Intergaration Employees', 'French', 'Employés d''Instacom Intergaration';
EXEC dbo.addLanuageLabel 'English',  'Instacom Intergaration Locations', 'French', 'Locations - Instacom Intergaration';
EXEC dbo.addLanuageLabel 'English',  'Intergration Bloodhound Sites', 'French', 'Sites d''Intégration Bloodhound';
EXEC dbo.addLanuageLabel 'English',  'Internet Explorer 7 or Compatibility View Detected.', 'French', 'Internet Explorer 7 ou Affichage de Compatibilité Détecté.';
EXEC dbo.addLanuageLabel 'English',  'Internet Explorer Browser Error', 'French', 'Erreur de Navigateur Internet Explorer';
EXEC dbo.addLanuageLabel 'English',  'Internet Explorer', 'French', 'Internet Explorer';
EXEC dbo.addLanuageLabel 'English',  'Interval In Minutes', 'French', 'Intervalle en Minutes';
EXEC dbo.addLanuageLabel 'English',  'Is a ITG Instacom Employee.', 'French', 'Est un employé d''ITG Instacom.';
EXEC dbo.addLanuageLabel 'English',  'Is a Risk Assessment Individual.', 'French', 'Est individu d''Évaluation des Risques';
EXEC dbo.addLanuageLabel 'English',  'Is linked to a Checklist Resource.', 'French', 'Est lié à une Programme de la Liste de Contrôle des Ressources';
EXEC dbo.addLanuageLabel 'English',  'Is linked to a Checklist Response Rule.', 'French', 'Est lié à une Programme de la Règles de Réponse de la Liste de Contrôle';
EXEC dbo.addLanuageLabel 'English',  'Is linked to a Checklist Schedule.', 'French', 'Est lié à une Programme de la Liste de Contrôle';
EXEC dbo.addLanuageLabel 'English',  'Is linked to a Court Appearance.', 'French', 'Est lié à une comparution devant le tribunal.';
EXEC dbo.addLanuageLabel 'English',  'Is linked to a Disciplinary Appearance.', 'French', 'Est lié à une comparution disciplinaire.';
EXEC dbo.addLanuageLabel 'English',  'Is linked to a Job Card Rule.', 'French', 'Est lié à une Règle de Carte de Travail';
EXEC dbo.addLanuageLabel 'English',  'Is linked to a Job Card.', 'French', 'Est lié à une Carte de Travail';
EXEC dbo.addLanuageLabel 'English',  'Is linked to a Locality Association.', 'French', 'Est lié à une Association de la Localité';
EXEC dbo.addLanuageLabel 'English',  'Is linked to a Notification Rule.', 'French', 'Est lié à une Règle de Notification';
EXEC dbo.addLanuageLabel 'English',  'Is linked to a Police Station Association.', 'French', 'Est lié à une Association des Postes de Police';
EXEC dbo.addLanuageLabel 'English',  'Is linked to a Scheduled Report.', 'French', 'Est lié à un Rapport Programmée';
EXEC dbo.addLanuageLabel 'English',  'Is part of Asset Tracking', 'French', 'Fait partie du Suivi des Actifs';
EXEC dbo.addLanuageLabel 'English',  'Job Card', 'French', 'Carte de Travail';
EXEC dbo.addLanuageLabel 'English',  'Key Details', 'French', 'Détails Clés';
EXEC dbo.addLanuageLabel 'English',  'Landing Page', 'French', 'Page d''Accueil';
EXEC dbo.addLanuageLabel 'English',  'Last 3 Months', 'French', '3 Derniers Mois';
EXEC dbo.addLanuageLabel 'English',  'Last 6 Months', 'French', '6 Derniers Mois';
EXEC dbo.addLanuageLabel 'English',  'Last Login', 'French', 'Dernière Date de Connexion';
EXEC dbo.addLanuageLabel 'English',  'Last Month', 'French', 'Le Mois Dernier';
EXEC dbo.addLanuageLabel 'English',  'Last Week', 'French', 'La Semaine Dernière';
EXEC dbo.addLanuageLabel 'English',  'Last X Days', 'French', 'X Derniers Jours';
EXEC dbo.addLanuageLabel 'English',  'Last X Financial Years', 'French', 'X Dernières Années Financières';
EXEC dbo.addLanuageLabel 'English',  'Last X Hours', 'French', 'Dernières X Heures';
EXEC dbo.addLanuageLabel 'English',  'Last X Months', 'French', 'X Derniers Mois';
EXEC dbo.addLanuageLabel 'English',  'Last X Weeks', 'French', 'X Dernières Semaines';
EXEC dbo.addLanuageLabel 'English',  'Last X Years', 'French', 'X Dernières Années';
EXEC dbo.addLanuageLabel 'English',  'Last Year', 'French', 'X Dernières Années';
EXEC dbo.addLanuageLabel 'English',  'Last name', 'French', 'Nom';
EXEC dbo.addLanuageLabel 'English',  'License Expiry Due!', 'French', 'Date Expiration de la Licence!';
EXEC dbo.addLanuageLabel 'English',  'License Information', 'French', 'Informations sur la Licence';
EXEC dbo.addLanuageLabel 'English',  'License errors, check license information page.', 'French', 'Erreurs de licence, consultez la page d''informations sur la licence.';
EXEC dbo.addLanuageLabel 'English',  'License updated successfully, Thank you!', 'French', 'Licence mise à jour avec succès, merci!';
EXEC dbo.addLanuageLabel 'English',  'Link Analysis', 'French', 'Analyse des Liens';
EXEC dbo.addLanuageLabel 'English',  'Link Step Sub Tab for Incident Involvement Process Flow', 'French', 'Lien sous-onglet de l''étape pour le flux du processus de participation aux incidents';
EXEC dbo.addLanuageLabel 'English',  'Loading, please wait...', 'French', 'Chargement, veuillez patienter...';
EXEC dbo.addLanuageLabel 'English',  'Locality Addresses', 'French', 'Adresses des Localités';
EXEC dbo.addLanuageLabel 'English',  'Locality Associations', 'French', 'Associations de la Localité';
EXEC dbo.addLanuageLabel 'English',  'Locality Attachments', 'French', 'Pièces Jointes de Localité';
EXEC dbo.addLanuageLabel 'English',  'Locality Control', 'French', 'Contrôle de Localité';
EXEC dbo.addLanuageLabel 'English',  'Locality Group Rules', 'French', 'Règles de Groupe de Localités';
EXEC dbo.addLanuageLabel 'English',  'Locality Groups', 'French', 'Groupes de Localité';
EXEC dbo.addLanuageLabel 'English',  'Locality Incident Profiles', 'French', 'Profils d''Incidents de Localité';
EXEC dbo.addLanuageLabel 'English',  'Locality Profiles', 'French', 'Profils des Localités';
EXEC dbo.addLanuageLabel 'English',  'Locality Restrictions', 'French', 'Restrictions de Localité';
EXEC dbo.addLanuageLabel 'English',  'Locality Risk Categories', 'French', 'Catégories de Risque de Localité';
EXEC dbo.addLanuageLabel 'English',  'Locality Rules', 'French', 'Règles des Localités';
EXEC dbo.addLanuageLabel 'English',  'Locality Site Description Fields', 'French', 'Champs de Description de Site de Localité';
EXEC dbo.addLanuageLabel 'English',  'Locality Structures', 'French', 'Structures des Localités';
EXEC dbo.addLanuageLabel 'English',  'Logged Out', 'French', 'Déconnecté';
EXEC dbo.addLanuageLabel 'English',  'Logging in', 'French', 'Se Connecter';
EXEC dbo.addLanuageLabel 'English',  'Login details incorrect!', 'French', 'Informations de connexion incorrectes!';
EXEC dbo.addLanuageLabel 'English',  'Login', 'French', 'Connexion';
EXEC dbo.addLanuageLabel 'English',  'Logout', 'French', 'Se déconnecter';
EXEC dbo.addLanuageLabel 'English',  'Medical Details', 'French', 'Détails Médicaux';
EXEC dbo.addLanuageLabel 'English',  'Menu search...', 'French', 'Recherche de menu…';
EXEC dbo.addLanuageLabel 'English',  'Message Utility Global Notification Rule Intersection', 'French', 'Intersection de la Règle de Notification Globale d''Utilitaire de Message';
EXEC dbo.addLanuageLabel 'English',  'Model', 'French', 'Modèle';
EXEC dbo.addLanuageLabel 'English',  'Modus Operandi Detailed', 'French', 'Modus Operandi Détaillé';
EXEC dbo.addLanuageLabel 'English',  'Modus Operandi Summary', 'French', 'Résumé du Modus Operandi';
EXEC dbo.addLanuageLabel 'English',  'Modus Operandi', 'French', 'Modus Operandi';
EXEC dbo.addLanuageLabel 'English',  'Motivation required.', 'French', 'Motivation requise.';
EXEC dbo.addLanuageLabel 'English',  'NO MENUS FOUND', 'French', 'AUCUN MENUS TROUVÉ';
EXEC dbo.addLanuageLabel 'English',  'Navigate back to Stack', 'French', 'Revenez à Stack';
EXEC dbo.addLanuageLabel 'English',  'Navigation', 'French', 'Navigation';
EXEC dbo.addLanuageLabel 'English',  'New Password', 'French', 'Nouveau Mot de Passe';
EXEC dbo.addLanuageLabel 'English',  'New', 'French', 'Nouveau';
EXEC dbo.addLanuageLabel 'English',  'Next 3 Months', 'French', '3 Prochains Mois';
EXEC dbo.addLanuageLabel 'English',  'Next 6 Months', 'French', '6 Prochains Mois';
EXEC dbo.addLanuageLabel 'English',  'Next Financial Year', 'French', 'Prochain Année Financière';
EXEC dbo.addLanuageLabel 'English',  'Next Month', 'French', 'Le Mois Prochain';
EXEC dbo.addLanuageLabel 'English',  'Next Week', 'French', 'Prochaine Semaine';
EXEC dbo.addLanuageLabel 'English',  'Next X Days', 'French', 'X Prochains Jours';
EXEC dbo.addLanuageLabel 'English',  'Next X Financial Years', 'French', 'X Prochains Années Financières';
EXEC dbo.addLanuageLabel 'English',  'Next X Hours', 'French', 'X Prochaines Heures';
EXEC dbo.addLanuageLabel 'English',  'Next X Months', 'French', 'X Prochains Mois';
EXEC dbo.addLanuageLabel 'English',  'Next X Weeks', 'French', 'X Prochaines Semaines';
EXEC dbo.addLanuageLabel 'English',  'Next X Years', 'French', 'X Prochaines Années';
EXEC dbo.addLanuageLabel 'English',  'Next Year', 'French', 'L''Année Prochaine';
EXEC dbo.addLanuageLabel 'English',  'No Assets have been selected.', 'French', 'Aucun Actif n''a été sélectionné.';
EXEC dbo.addLanuageLabel 'English',  'Not Found - 404', 'French', 'Non Trouvé - 404';
EXEC dbo.addLanuageLabel 'English',  'Notification Details', 'French', 'Détails de la Notification';
EXEC dbo.addLanuageLabel 'English',  'Occurrence Category Scope', 'French', 'Portée de la Catégorie d''Occurrence';
EXEC dbo.addLanuageLabel 'English',  'Occurrence Escalation Procedure', 'French', 'Procédure d''Escalade d''Occurrence';
EXEC dbo.addLanuageLabel 'English',  'Organisation Contact DetailID', 'French', 'Coordonnées d''Organisation';
EXEC dbo.addLanuageLabel 'English',  'PIN has expired, please resend!', 'French', 'Le code PIN a expiré, veuillez le renvoyer!';
EXEC dbo.addLanuageLabel 'English',  'PIN successfully sent to', 'French', 'PIN envoyé avec succès à';
EXEC dbo.addLanuageLabel 'English',  'PIN was not successfully sent to', 'French', 'Le code PIN n''a pas été envoyé avec succès à';
EXEC dbo.addLanuageLabel 'English',  'Page', 'French', 'Page';
EXEC dbo.addLanuageLabel 'English',  'Panic Resource', 'French', 'Ressource de Panique';
EXEC dbo.addLanuageLabel 'English',  'Passport number that was specified, already exists.', 'French', 'Le numéro de passeport spécifié existe déjà.';
EXEC dbo.addLanuageLabel 'English',  'Passport', 'French', 'Passeport';
EXEC dbo.addLanuageLabel 'English',  'Password strength should at least be', 'French', 'La force du Mot de Passe doit au moins être';
EXEC dbo.addLanuageLabel 'English',  'Password', 'French', 'Mot de Passe';
EXEC dbo.addLanuageLabel 'English',  'Please cancel the  Two Factor Authentication process & try again.', 'French', 'Veuillez annuler le processus d''authentification à deux facteurs et réessayer.';
EXEC dbo.addLanuageLabel 'English',  'Please contact Online Intelligence to renew your license.', 'French', 'Veuillez contacter Online Intelligence pour renouveler votre licence.';
EXEC dbo.addLanuageLabel 'English',  'Please contact your system administrator.', 'French', 'Veuillez contacter votre administrateur système.';
EXEC dbo.addLanuageLabel 'English',  'Please enable JavaScript to use file uploader.', 'French', 'Veuillez activer JavaScript pour utiliser le téléchargeur de fichiers.';
EXEC dbo.addLanuageLabel 'English',  'Please ensure that all fields are filled in!', 'French', 'Veuillez vous assurer que tous les champs sont remplis!';
EXEC dbo.addLanuageLabel 'English',  'Please ensure that at least one option is selected for each of the following Locality Groupings', 'French', 'Veuillez vous assurer qu''au moins une option est sélectionnée pour chacun des Regroupements de Localités suivants';
EXEC dbo.addLanuageLabel 'English',  'Please ensure that the passwords entered match.', 'French', 'Veuillez vous assurer que les mots de passe saisis correspondent.';
EXEC dbo.addLanuageLabel 'English',  'Please enter Feedback', 'French', 'Veuillez saisir de Rétroaction';
EXEC dbo.addLanuageLabel 'English',  'Please enter a SMS message', 'French', 'Veuillez saisir un SMS';
EXEC dbo.addLanuageLabel 'English',  'Please enter a email message', 'French', 'Veuillez saisir un courriel';
EXEC dbo.addLanuageLabel 'English',  'Please enter a valid PIN!', 'French', 'Veuillez saisir un code PIN valide!';
EXEC dbo.addLanuageLabel 'English',  'Please enter a valid decimal value', 'French', 'Veuillez saisir une valeur décimale valide';
EXEC dbo.addLanuageLabel 'English',  'Please enter a valid integer value between', 'French', 'Veuillez saisir une valeur entière valide entre';
EXEC dbo.addLanuageLabel 'English',  'Please enter a valid license key!', 'French', 'Veuillez saisir une clé de licence valide!';
EXEC dbo.addLanuageLabel 'English',  'Please enter a valid number between 0 and 10', 'French', 'Veuillez saisir un nombre valide compris entre 0 et 10';
EXEC dbo.addLanuageLabel 'English',  'Please log out the other session/s to continue...', 'French', 'Veuillez déconnecter les autres sessions pour continuer...';
EXEC dbo.addLanuageLabel 'English',  'Please note that the recalculation of Category per Locality Scoping Rules may take some time. Ensure that you have set up all Category per Locality Scoping Rules before recalculation. Do you wish to continue ?', 'French', 'Veuillez noter que le recalcul des règles de cadrage des catégories par localité peut prendre un certain temps. Assurez-vous que vous avez configuré toutes les règles de portée des catégories par localité avant de recalculer. Souhaitez-vous continuer ?';
EXEC dbo.addLanuageLabel 'English',  'Please paste your license key here', 'French', 'Veuillez coller votre clé de licence ici';
EXEC dbo.addLanuageLabel 'English',  'Please provide a detailed description of the incident', 'French', 'Veuillez Fournir une Description Détaillée de l''Incident';
EXEC dbo.addLanuageLabel 'English',  'Please select a recipient with a cell number', 'French', 'Veuillez sélectionner un destinataire avec un numéro de portable';
EXEC dbo.addLanuageLabel 'English',  'Please select a recipient with an valid email address', 'French', 'Veuillez sélectionner un destinataire avec un courriel valide';
EXEC dbo.addLanuageLabel 'English',  'Please select at least one Locality or Locality Group.', 'French', 'Veuillez sélectionner au moins une Localité ou un Groupe de Localités.';
EXEC dbo.addLanuageLabel 'English',  'Please select at least one Recipient', 'French', 'Veuillez sélectionner au moins un Destinataire';
EXEC dbo.addLanuageLabel 'English',  'Please select either the SMS or Email option', 'French', 'Veuillez sélectionner l''option SMS ou Courriel';
EXEC dbo.addLanuageLabel 'English',  'Please supply a value for the field : External Reference Numbers.', 'French', 'Veuillez fournir une valeur pour le champ: Numéros de Référence Externes.';
EXEC dbo.addLanuageLabel 'English',  'Please supply a value for the field : External Reference Numbers.', 'French', 'Veuillez fournir une valeur pour le champ: Numéros de référence externes.';
EXEC dbo.addLanuageLabel 'English',  'Point Of Interest', 'French', 'Point d''Intérêt';
EXEC dbo.addLanuageLabel 'English',  'Police Associations', 'French', 'Associations de Police';
EXEC dbo.addLanuageLabel 'English',  'Primary Colour', 'French', 'Couleur Primaire';
EXEC dbo.addLanuageLabel 'English',  'Process Flow', 'French', 'Flux de Processus';
EXEC dbo.addLanuageLabel 'English',  'Progress', 'French', 'Progrès';
EXEC dbo.addLanuageLabel 'English',  'Property Name', 'French', 'Nom Propriété';
EXEC dbo.addLanuageLabel 'English',  'Property Value', 'French', 'Valeur de la Propriété';
EXEC dbo.addLanuageLabel 'English',  'Property', 'French', 'Propriété';
EXEC dbo.addLanuageLabel 'English',  'Record Not Found', 'French', 'Enregistrement Non Trouvé';
EXEC dbo.addLanuageLabel 'English',  'Record is Read-Only', 'French', 'L''enregistrement est en Lecture Seule';
EXEC dbo.addLanuageLabel 'English',  'Registration Number', 'French', 'Numéro d''Enregistrement';
EXEC dbo.addLanuageLabel 'English',  'Registration', 'French', 'Enregistrement';
EXEC dbo.addLanuageLabel 'English',  'Remaining Monthly Integration Credits:', 'French', 'Crédits d''Intégration Mensuels Restants:';
EXEC dbo.addLanuageLabel 'English',  'Report', 'French', 'Rapport';
EXEC dbo.addLanuageLabel 'English',  'Request Description', 'French', 'Demander une Description';
EXEC dbo.addLanuageLabel 'English',  'Request New Password', 'French', 'Demander un Nouveau Mot de Passe';
EXEC dbo.addLanuageLabel 'English',  'Request Password', 'French', 'Demander Mot de Passe';
EXEC dbo.addLanuageLabel 'English',  'Resend', 'French', 'Renvoyer';
EXEC dbo.addLanuageLabel 'English',  'Reset your', 'French', 'Réinitialisez votre';
EXEC dbo.addLanuageLabel 'English',  'Resource Display Label', 'French', 'Étiquette d''Affichage des Ressources';
EXEC dbo.addLanuageLabel 'English',  'Resource Response Time', 'French', 'Temps de Réponse des Ressources';
EXEC dbo.addLanuageLabel 'English',  'Response Occurrence Rule', 'French', 'Réponse Règle d''Occurrence';
EXEC dbo.addLanuageLabel 'English',  'Response Vehicle Localities', 'French', 'Localités des Véhicules d''Intervention';
EXEC dbo.addLanuageLabel 'English',  'Response', 'French', 'Réponse';
EXEC dbo.addLanuageLabel 'English',  'Risk Assessments', 'French', 'Evaluations des Risques';
EXEC dbo.addLanuageLabel 'English',  'SMS was not successfully sent to', 'French', 'Le SMS n''a pas été envoyé avec succès à';
EXEC dbo.addLanuageLabel 'English',  'Save', 'French', 'Enregistrer';
EXEC dbo.addLanuageLabel 'English',  'Schema', 'French', 'Schéma';
EXEC dbo.addLanuageLabel 'English',  'Scope Profile Locality Group Scoping', 'French', 'Portée Profil de Portée du Groupe de Localités';
EXEC dbo.addLanuageLabel 'English',  'Search here', 'French', 'Cherche ici';
EXEC dbo.addLanuageLabel 'English',  'Security Gurad Localities', 'French', 'Localités d''Agents de Sécurité';
EXEC dbo.addLanuageLabel 'English',  'Security Measure Detailed', 'French', 'Mesure de Sécurité Détaillée';
EXEC dbo.addLanuageLabel 'English',  'Security Measure Summary', 'French', 'Résumé des Mesures de Sécurité';
EXEC dbo.addLanuageLabel 'English',  'Security Measure', 'French', 'Mesure de Sécurité';
EXEC dbo.addLanuageLabel 'English',  'Select a Condition for the Asset.', 'French', 'Sélectionnez une Condition pour l''Actif.';
EXEC dbo.addLanuageLabel 'English',  'Selected is in the Future.', 'French', 'Sélectionné est dans le futur.';
EXEC dbo.addLanuageLabel 'English',  'Serious login error!', 'French', 'Erreur de connexion grave!';
EXEC dbo.addLanuageLabel 'English',  'Session Expired', 'French', 'La Session a Expiré';
EXEC dbo.addLanuageLabel 'English',  'Set Password', 'French', 'Définir le Mot de Passe';
EXEC dbo.addLanuageLabel 'English',  'Show App URL', 'French', 'Afficher l''URL de l''Application';
EXEC dbo.addLanuageLabel 'English',  'Show App URL', 'French', 'Afficher l''URL de l''application';
EXEC dbo.addLanuageLabel 'English',  'Show Final Category Popup', 'French', 'Afficher la fenêtre contextuelle de la Catégorie Finale';
EXEC dbo.addLanuageLabel 'English',  'Show New Button', 'French', 'Afficher le nouveau bouton';
EXEC dbo.addLanuageLabel 'English',  'Signaltower Default Workflow', 'French', 'Flux de Travail par Défaut Signaltower';
EXEC dbo.addLanuageLabel 'English',  'Simple Locality', 'French', 'Localité Simple';
EXEC dbo.addLanuageLabel 'English',  'Simple Step', 'French', 'Étape Simple';
EXEC dbo.addLanuageLabel 'English',  'Special Instructions', 'French', 'Instructions Spéciales';
EXEC dbo.addLanuageLabel 'English',  'Status Type', 'French', 'Type de Statut';
EXEC dbo.addLanuageLabel 'English',  'Status', 'French', 'Statut';
EXEC dbo.addLanuageLabel 'English',  'Step Filter', 'French', 'Filtre d''Étape';
EXEC dbo.addLanuageLabel 'English',  'Subcategory Score', 'French', 'Score de la Sous-Catégorie';
EXEC dbo.addLanuageLabel 'English',  'Subcategory', 'French', 'Sous-Catégorie';
EXEC dbo.addLanuageLabel 'English',  'Subsequent Events', 'French', 'Événements Ultérieurs';
EXEC dbo.addLanuageLabel 'English',  'Super Search', 'French', 'Super Recherche';
EXEC dbo.addLanuageLabel 'English',  'Survey Feedback', 'French', 'Commentaires sur l''Enquête';
EXEC dbo.addLanuageLabel 'English',  'Tasks', 'French', 'Tâches';
EXEC dbo.addLanuageLabel 'English',  'Technical', 'French', 'Technique';
EXEC dbo.addLanuageLabel 'English',  'The Account Number does not meet the required format\n\n Example :', 'French', 'Le Numéro de Compte ne correspond pas au format requis \ n \ n Exemple:';
EXEC dbo.addLanuageLabel 'English',  'The Contact Number does not meet the required format\n\n Example :', 'French', 'Le Numéro de Contact ne correspond pas au format requis \ n \ n Exemple:';
EXEC dbo.addLanuageLabel 'English',  'The Database is already being indexed.', 'French', 'La Base de Données est déjà en cours d''indexation.';
EXEC dbo.addLanuageLabel 'English',  'The Individual cannot be deleted  because of the following:', 'French', 'L''individu ne peut pas être supprimé pour les raisons suivantes:';
EXEC dbo.addLanuageLabel 'English',  'The contact number does not meet the required format\n\n Example :', 'French', 'Le numéro de contact ne correspond pas au format requis \ n \ n Exemple:';
EXEC dbo.addLanuageLabel 'English',  'The directory defined in the CentralPath.Index System Property is invalid! Please ensure the directory is accesible.', 'French', 'Le répertoire défini dans la propriété système CentralPath.Index n''est pas valide! Veuillez vous assurer que le répertoire est accessible.';
EXEC dbo.addLanuageLabel 'English',  'The first name that was specified, already exists.', 'French', 'Le prenom spécifié existe déjà.';
EXEC dbo.addLanuageLabel 'English',  'The following licenses are about to expire', 'French', 'Les licences suivantes sont sur le point d''expirer';
EXEC dbo.addLanuageLabel 'English',  'The following required Escalation Steps are incomplete', 'French', 'Les Étapes d''Escalade requises suivantes sont incomplètes';
EXEC dbo.addLanuageLabel 'English',  'The last name that was specified, already exists.', 'French', 'Le nom de famille spécifié existe déjà.';
EXEC dbo.addLanuageLabel 'English',  'The maximum amount of sessions allows concurrently is', 'French', 'Le nombre maximum de sessions autorisées simultanément est';
EXEC dbo.addLanuageLabel 'English',  'The password could not be updated because the supplied old password is incorrect!', 'French', 'Le mot de passe n''a pas pu être mis à jour car l''ancien mot de passe fourni est incorrect!';
EXEC dbo.addLanuageLabel 'English',  'The password could not be updated because the user was not found!', 'French', 'Le mot de passe n''a pas pu être mis à jour car l''utilisateur n''a pas été trouvé!';
EXEC dbo.addLanuageLabel 'English',  'The record you requested could not be found. To go back to the previous screen please click', 'French', 'L''enregistrement que vous avez demandé est introuvable. Pour revenir à l''écran précédent, cliquez';
EXEC dbo.addLanuageLabel 'English',  'The server seems to be down, please try again later.', 'French', 'Le serveur semble être en panne, veuillez réessayer plus tard.';
EXEC dbo.addLanuageLabel 'English',  'The supplied link has already been used or has expired, please get another link!', 'French', 'Le lien fourni a déjà été utilisé ou a expiré, veuillez obtenir un autre lien!';
EXEC dbo.addLanuageLabel 'English',  'The supplied link is invalid!', 'French', 'Le lien fourni est invalide!';
EXEC dbo.addLanuageLabel 'English',  'There are no licences loaded on the system.', 'French', 'Aucune licence n''est chargée sur le système.';
EXEC dbo.addLanuageLabel 'English',  'There are no valid licences loaded on the system.', 'French', 'Aucune licence valide n''est chargée sur le système.';
EXEC dbo.addLanuageLabel 'English',  'There is an item for your attention.', 'French', 'Il y a un élément à votre attention.';
EXEC dbo.addLanuageLabel 'English',  'This Financial Year', 'French', 'Cette Année Financière';
EXEC dbo.addLanuageLabel 'English',  'This Locality cannot be deleted, it is used in :', 'French', 'Cette Localité ne peut pas être supprimée, elle est utilisée dans:';
EXEC dbo.addLanuageLabel 'English',  'This Month', 'French', 'Ce Mois-Ci';
EXEC dbo.addLanuageLabel 'English',  'This Week', 'French', 'Cette Semaine';
EXEC dbo.addLanuageLabel 'English',  'This Year', 'French', 'Cette Année';
EXEC dbo.addLanuageLabel 'English',  'This application is not compatible with Internet Explorer 6 or older.', 'French', 'Cette application n''est pas compatible avec Internet Explorer 6 ou une version antérieure.';
EXEC dbo.addLanuageLabel 'English',  'This application is not compatible with Internet Explorer version 6 or lower.', 'French', 'Cette application n''est pas compatible avec Internet Explorer version 6 ou inférieure.';
EXEC dbo.addLanuageLabel 'English',  'This attachment cannot be deleted because it is linked to another entry.', 'French', 'Cette Pièce Jointe ne peut pas être supprimée car elle est liée à une autre Entrée.';
EXEC dbo.addLanuageLabel 'English',  'This dashboard can not be a child of itself. Please remove the group or choose an appropriate one.', 'French', 'Ce tableau de bord ne peut pas être un Subdomain de lui-même. Veuillez supprimer le groupe ou en choisir un approprié.';
EXEC dbo.addLanuageLabel 'English',  'This dashboard is a parent to other dashboards.  Please remove the child dashboards first', 'French', 'Ce tableau de bord est parent d''autres tableaux de bord. Veuillez d''abord supprimer les tableaux de bord liés';
EXEC dbo.addLanuageLabel 'English',  'This event has already been acknowledged by', 'French', 'Cet événement a déjà été reconnu par';
EXEC dbo.addLanuageLabel 'English',  'This saved query cannot be deleted, it is linked to', 'French', 'Cette requête enregistrée ne peut pas être supprimée, elle est liée à';
EXEC dbo.addLanuageLabel 'English',  'Today', 'French', 'Aujourd''hui';
EXEC dbo.addLanuageLabel 'English',  'Tomorrow', 'French', 'Demain';
EXEC dbo.addLanuageLabel 'English',  'Transition Options', 'French', 'Options de Transition';
EXEC dbo.addLanuageLabel 'English',  'Transition options', 'French', 'Options de transition';
EXEC dbo.addLanuageLabel 'English',  'Transition', 'French', 'Transition';
EXEC dbo.addLanuageLabel 'English',  'Translate', 'French', 'Traduire';
EXEC dbo.addLanuageLabel 'English',  'Turnaround Time', 'French', 'Délai d''Exécution';
EXEC dbo.addLanuageLabel 'English',  'Unable to find contact number for the specified system user', 'French', 'Impossible de trouver le numéro de contact de l''utilisateur système spécifié';
EXEC dbo.addLanuageLabel 'English',  'Unable to find email address for the specified system user', 'French', 'Impossible de trouver l''adresse courriel de l''Utilisateur Système spécifié';
EXEC dbo.addLanuageLabel 'English',  'Unable to save Escalation Step as Response cannot be validated with the regular expression.', 'French', 'Impossible d''enregistrer l''Étape d''Escalade en tant que réponse ne peut pas être validée avec l''expression régulière.';
EXEC dbo.addLanuageLabel 'English',  'Unable to save Escalation Step as the Step has Predecessors.', 'French', 'Impossible d''enregistrer l''Étape d''Escalade car l''Étape a des Prédécesseurs.';
EXEC dbo.addLanuageLabel 'English',  'Unable to save Escalation Step as the User doesnt have scope.', 'French', 'Impossible d''enregistrer l''Étape d''Escalade car l''utilisateur n''a pas de Portée.';
EXEC dbo.addLanuageLabel 'English',  'Unable to send Email to', 'French', 'Impossible d''envoyer le courriel à';
EXEC dbo.addLanuageLabel 'English',  'Unable to send SMS as the settings are not defined', 'French', 'Impossible d''envoyer des SMS car les paramètres ne sont pas définis';
EXEC dbo.addLanuageLabel 'English',  'Unable to send SMS to', 'French', 'Impossible d''envoyer des SMS à';
EXEC dbo.addLanuageLabel 'English',  'Unable to start two factor authentication', 'French', 'Impossible de démarrer l''authentification à deux facteurs';
EXEC dbo.addLanuageLabel 'English',  'Unexpected error occurred while attempting two factor authentication, please resend!', 'French', 'Une erreur inattendue s''est produite lors de la tentative d''authentification à deux facteurs, veuillez renvoyer!';
EXEC dbo.addLanuageLabel 'English',  'Use Historic Events', 'French', 'Utiliser les Événements Historiques';
EXEC dbo.addLanuageLabel 'English',  'User Locality Scoping', 'French', 'Portée de la Localité Utilisateur';
EXEC dbo.addLanuageLabel 'English',  'Vehicle Category Scope', 'French', 'Portée de la Catégorie de Véhicule';
EXEC dbo.addLanuageLabel 'English',  'Vehicle Display Label Cache', 'French', 'Cache d''Étiquettes d''Affichage du Véhicule';
EXEC dbo.addLanuageLabel 'English',  'Vehicle Display Label', 'French', 'Étiquette d''Affichage du Véhicule';
EXEC dbo.addLanuageLabel 'English',  'Vehicle Esclation Procedure Scope', 'French', 'Portée de la Procédure d''Esclation du Véhicule';
EXEC dbo.addLanuageLabel 'English',  'Vehicle Property', 'French', 'Propriété Véhicule';
EXEC dbo.addLanuageLabel 'English',  'Vehicle already exist with the specified category.', 'French', 'Le véhicule existe déjà avec la catégorie spécifiée.';
EXEC dbo.addLanuageLabel 'English',  'Vehicle already exist with the specified credentails.', 'French', 'Le véhicule existe déjà avec les informations d''identification spécifiées.';
EXEC dbo.addLanuageLabel 'English',  'Vehicle already exist with the specified model.', 'French', 'Le véhicule existe déjà avec le modèle spécifié.';
EXEC dbo.addLanuageLabel 'English',  'Vehicle already exist with the specified primary colour.', 'French', 'Le véhicule existe déjà avec la couleur primaire spécifiée.';
EXEC dbo.addLanuageLabel 'English',  'Vehicle already exist with the specified registration number.', 'French', 'Le véhicule existe déjà avec le numéro d''immatriculation spécifié.';
EXEC dbo.addLanuageLabel 'English',  'Vehicle', 'French', 'Véhicule';
EXEC dbo.addLanuageLabel 'English',  'Vehicles', 'French', 'Véhicules';
EXEC dbo.addLanuageLabel 'English',  'View Locality GPS', 'French', 'Voir le GPS de la Localité';
EXEC dbo.addLanuageLabel 'English',  'View', 'French', 'Voir';
EXEC dbo.addLanuageLabel 'English',  'Was there more survivors involved?', 'French', 'Y Avait-il Plus de Survivants Impliqués?';
EXEC dbo.addLanuageLabel 'English',  'We''re sorry, but the page requested could not be found. To go back to the previous screen please click', 'French', 'Nous sommes désolés, mais la page demandée est introuvable. Pour revenir à l''écran précédent, cliquez';
EXEC dbo.addLanuageLabel 'English',  'Weighted Rating', 'French', 'Évaluation Pondération';
EXEC dbo.addLanuageLabel 'English',  'What is the Perpetrator relationship to the survivor(s)?', 'French', 'Quelle est la relation de l''Auteur avec le(s) Survivant(s)?';
EXEC dbo.addLanuageLabel 'English',  'Workflow Rule', 'French', 'Règle du Flux de Travail';
EXEC dbo.addLanuageLabel 'English',  'Workflow', 'French', 'Flux de Travail';
EXEC dbo.addLanuageLabel 'English',  'Yesterday', 'French', 'Hier';
EXEC dbo.addLanuageLabel 'English',  'You are not currently logged in, your session may have expired or you have been logged out.', 'French', 'Vous n''êtes pas connecté actuellement, votre session a peut-être expiré ou vous avez été déconnecté.';
EXEC dbo.addLanuageLabel 'English',  'You don''t have access to modify this information. To go back to the previous screen please click', 'French', 'Vous n''avez pas accès pour modifier ces informations. Pour revenir à l''écran précédent, cliquez';
EXEC dbo.addLanuageLabel 'English',  'You don''t have access to view this information. To go back to the previous screen please click', 'French', 'Vous n''avez pas accès pour afficher ces informations. Pour revenir à l''écran précédent, cliquez';
EXEC dbo.addLanuageLabel 'English',  'You have been successfully logged out, to log in again please click', 'French', 'Vous avez été déconnecté avec succès, pour vous reconnecter, cliquez';
EXEC dbo.addLanuageLabel 'English',  'You may experience some known issues while using this version of explorer.', 'French', 'Vous pouvez rencontrer des problèmes connus lors de l''utilisation de cette version de l''explorateur.';
EXEC dbo.addLanuageLabel 'English',  'Your license for', 'French', 'Votre licence pour';
EXEC dbo.addLanuageLabel 'English',  'Your system is being indexed', 'French', 'Votre système est en cours d''indexation';
EXEC dbo.addLanuageLabel 'English',  'cannot index system if super search is not enabled!', 'French', 'impossible d''indexer le système si la super recherche n''est pas activée!';
EXEC dbo.addLanuageLabel 'English',  'continue', 'French', 'continuer';
EXEC dbo.addLanuageLabel 'English',  'currently at', 'French', 'actuellement à';
EXEC dbo.addLanuageLabel 'English',  'day', 'French', 'jour';
EXEC dbo.addLanuageLabel 'English',  'in the future cannot be selected.', 'French', 'à l''avenir ne peut pas être sélectionné.';
EXEC dbo.addLanuageLabel 'English',  'invalid system user!', 'French', 'utilisateur système invalide!';
EXEC dbo.addLanuageLabel 'English',  'link.', 'French', 'Lien.';
EXEC dbo.addLanuageLabel 'English',  'mode detected, the system may not function properly. Please disable compatibility view or upgrade your browser. \nCompatibility view can be disabled via ''Tools'' > ''Compatibility View', 'French', 'mode détecté, le système peut ne pas fonctionner correctement. Veuillez désactiver l''affichage de compatibilité ou mettre à jour votre navigateur. \ nLa vue de compatibilité peut être désactivée via ''Outils''> ''Vue de compatibilité';
EXEC dbo.addLanuageLabel 'English',  'of', 'French', 'de';
EXEC dbo.addLanuageLabel 'English',  'password', 'French', 'Mot de Passe';
EXEC dbo.addLanuageLabel 'English',  'system user deleted!', 'French', 'utilisateur système supprimé!';
EXEC dbo.addLanuageLabel 'English',  'will expire in', 'French', 'expirera dans';
